services:
  - type: web
    name: fastapi-backend
    env: python
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      prisma generate
      prisma py fetch
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-postgres-db
          property: connectionString
    plan: free

  - type: web
    name: react-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://fastapi-backend-irwb.onrender.com/api/*

databases:
  - name: my-postgres-db
    plan: free
